"use strict";
const fs = require("fs");
const path = require("path");
const sharp = require("sharp");

const BASE = path.join(__dirname, "..", "Joey Assets", "Gifford");
const OUT = path.join(__dirname, "..", "kq-gf-ui-art.js");
async function webp(filename, w, h, quality = 88, fit = "inside") {
  const buf = await sharp(path.join(BASE, filename)).resize(w, h, { fit, withoutEnlargement: true, background: { r:0,g:0,b:0,alpha:0 } }).webp({ quality, effort:4 }).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}
async function trim(filename, w, h, quality = 90) {
  const buf = await sharp(path.join(BASE, filename)).trim({ background:{r:0,g:0,b:0,alpha:0} }).resize(w,h,{fit:"contain",background:{r:0,g:0,b:0,alpha:0}}).webp({quality,effort:4}).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}
async function main() {
  const art = {};
  for (const [key,file] of Object.entries({laneArith:"GF Arith.png",laneGeo:"GF Geo.png",laneLogic:"GF Logic.png",laneSci:"GF Sci.png",laneSpeed:"GF Speed.png",laneArithWin:"GF Arith Winning.png",laneGeoWin:"GF Geo Winning.png",laneLogicWin:"GF Logic Winning.png",laneSciWin:"GF Sci Winning.png",laneSpeedWin:"GF Speed Winning.png",laneArithLose:"GF Arith Losing.png",laneGeoLose:"GF Geo Losing.png",laneLogicLose:"GF Logic Losing.png",laneSciLose:"GF Science Losing.png",laneSpeedLose:"GF Speed Losing.png"})) art[key]=await trim(file,240,100);
  art.backBtn=await trim("GF Back.png",300,100); art.passBtn=await trim("GF Pass.png",300,100); art.okBtn=await trim("GF OK.png",300,100); art.cancelBtn=await trim("GF Cancel.png",300,100);
  art.wonRound=await trim("GF Win Token.png",100,100); art.lostRound=await trim("GF lose Token.png",100,100);
  art.round1=await trim("GF Round 1.png",600,280); art.round2=await trim("GF Round 2.png",600,280); art.round3=await trim("GF Round 3.png",600,280);
  art.winBoard=await trim("GF Win Round.png",900,620); art.loseBoard=await trim("GF Lose Round.png",900,620); art.drawBoard=await trim("GF Draw Round.png",900,620);
  art.mulligan=await trim("GF Mulligan Transparent.png",720,320); art.challenge=await trim("GF Challenge.png",520,240); art.reveal=await trim("GF Reveal.png",420,220); art.friendly=await trim("GF Friendly.png",420,220);
  art.winFinale=await webp("GF Win Finale.png",1024,576,86,"cover"); art.loseFinale=await webp("GF Lose Finale.png",1024,576,86,"cover"); art.drawFinale=await webp("GF Draw Finale.png",1024,576,86,"cover");
  art.roundTracker=await trim("GF Score Board.png",500,320); art.scoreFrame=await trim("GF Lane Score.png",140,100);
  art.battleLedger=await webp("GF Battle Ledger Transparent.png",721,2182,90,"fill"); art.ingenuity=await trim("GF Ingenuity.png",520,200);
  art.powerUp=await trim("GF Power Up.png",100,100); art.powerDown=await trim("GF Power Down.png",100,100); art.nameFrame=await trim("GF Nameplate.png",280,80);
  art.playMat=await webp("GF Play Mat.png",1672,941,84,"fill"); art.frame3=await webp("GF Frame 3 Lanes Wide.png",1400,1400,90,"inside");
  art.laneBounds=[28.2,43,56.6,71.8]; art.laneTokenX=[35.6,49.8,64.2]; art.laneMarkerWidth=13.4; art.laneMarkerHeight=7.9; art.laneMarkerFit="contain";
  art.ledgerLayout={width:721,height:2182,powerXs:[398,488],upperPowerYs:[332,412,498,582,664],lowerPowerYs:[1286,1346,1432,1512,1598],setXs:[306,398,490],upperSetYs:[856,936,1020],lowerSetYs:[1866,1952,2034]};
  fs.writeFileSync(OUT,`// Generated by scripts/embed_gf_ui.cjs — do not edit by hand.\nexport const GF_UI_ART = ${JSON.stringify(art)};\n`);
}
main().catch(error=>{console.error(error);process.exit(1)});
