// Reads Joey battle PNG assets, compresses them, and writes kq-joey-art.js
// with embedded base64 data URIs. Run once: node scripts/embed_joey_art.cjs
"use strict";
const fs = require("fs");
const path = require("path");
const sharp = require("sharp");

const ASSETS = path.join(__dirname, "..", "Joey Assets");
const OUT = path.join(__dirname, "..", "kq-joey-art.js");

// Map from filename fragment to role
const FILES = {
  background: {
    primary:      "ChatGPT Image Aug 19, 2026, 07_05_06 AM (4).png",  // wide orchard scene
    junior:       "ChatGPT Image Aug 19, 2026, 07_05_07 AM (5).png",  // purple twilight mountain
    intermediate: "ChatGPT Image Aug 19, 2026, 07_05_07 AM (6).png",  // steampunk city at dusk
  },
  overlay: {
    primary:      "ChatGPT Image Aug 19, 2026, 07_05_07 AM (7).png",  // vine/leaf/apple 5-lane frame
    junior:       "ChatGPT Image Aug 19, 2026, 07_05_08 AM (8).png",  // colour-coded lanes + lanterns
    intermediate: "ChatGPT Image Aug 19, 2026, 07_05_08 AM (9).png",  // steampunk brass pipes/gears
  },
  placeholder: {
    primary:      "ChatGPT Image Aug 19, 2026, 07_05_05 AM (1).png",  // rabbit picking apples
    junior:       "ChatGPT Image Aug 19, 2026, 05_46_49 PM.png",      // purple blob creature
    intermediate: "ChatGPT Image Aug 19, 2026, 06_51_59 AM (3).png",  // Victorian street urchin
  },
  // Individual card frames — LR and GF pending art generation
  cardFrame: {
    primary: "9FO/9f Card Frame.png",  // orchard/leaf card frame
  },
  // Deck builder UI
  okBtn: {
    primary:      "9FO/9f OK.png",
    junior:       "LR/LR OK",
    intermediate: "Gifford/GF OK.png",
  },
  cancelBtn: {
    primary:      "9FO/9f Cancel.png",
    junior:       "LR/LR Cancel",
    intermediate: "Gifford/GF Cancel.png",
  },
  deckPowers: {
    primary:      "9FO/9f Deck Powers.png",
    junior:       "LR/LR Deck Powers.png",
    intermediate: "Gifford/GF Deck Pow.png",
  },
};

async function toJpegDataUri(file, w, h, quality) {
  const p = path.join(ASSETS, file);
  const buf = await sharp(p).resize(w, h, { fit: "cover" }).jpeg({ quality }).toBuffer();
  const kb = (buf.length / 1024).toFixed(0);
  console.log(`  ${file} -> ${w}x${h} JPEG q${quality}: ${kb} KB`);
  return `data:image/jpeg;base64,${buf.toString("base64")}`;
}

async function toWebpDataUri(file, w, h, quality, fit = "fill") {
  const p = path.join(ASSETS, file);
  // Overlays need alpha channel preserved
  const buf = await sharp(p).resize(w, h, { fit }).webp({ quality, effort: 4 }).toBuffer();
  const kb = (buf.length / 1024).toFixed(0);
  console.log(`  ${file} -> ${w}x${h} WebP q${quality}: ${kb} KB`);
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

async function main() {
  const art = { primary: {}, junior: {}, intermediate: {} };
  const mods = ["primary", "junior", "intermediate"];

  console.log("\n--- Backgrounds (1024x576 JPEG) ---");
  for (const m of mods) {
    art[m].background = await toJpegDataUri(FILES.background[m], 1024, 576, 72);
  }

  console.log("\n--- UI Overlays (1024x576 WebP, alpha) ---");
  for (const m of mods) {
    art[m].overlay = await toWebpDataUri(FILES.overlay[m], 1024, 576, 70);
  }

  console.log("\n--- Placeholder card art (256x256 JPEG) ---");
  for (const m of mods) {
    art[m].placeholder = await toJpegDataUri(FILES.placeholder[m], 256, 256, 78);
  }

  console.log("\n--- Card frames (240x360 WebP, alpha) ---");
  for (const m of mods) {
    if (FILES.cardFrame?.[m]) {
      art[m].cardFrame = await toWebpDataUri(FILES.cardFrame[m], 240, 360, 80);
    } else {
      art[m].cardFrame = null;
    }
  }

  console.log("\n--- Deck builder buttons (400x160 WebP, alpha, inside fit) ---");
  for (const m of mods) {
    art[m].okBtn     = await toWebpDataUri(FILES.okBtn[m],     400, 160, 85, "inside");
    art[m].cancelBtn = await toWebpDataUri(FILES.cancelBtn[m], 400, 160, 85, "inside");
  }

  console.log("\n--- Deck Powers frame (480x400 WebP, alpha, inside fit) ---");
  for (const m of mods) {
    art[m].deckPowers = await toWebpDataUri(FILES.deckPowers[m], 480, 400, 80, "inside");
  }

  const lines = [
    "// Generated by scripts/embed_joey_art.cjs — do not edit by hand.",
    "// Joey battle arena backgrounds, UI overlays, placeholder card art, card frames, and deck builder UI.",
    "export const JOEY_ART = {",
  ];
  for (const m of mods) {
    lines.push(`  ${m}: {`);
    lines.push(`    background: "${art[m].background}",`);
    lines.push(`    overlay: "${art[m].overlay}",`);
    lines.push(`    placeholder: "${art[m].placeholder}",`);
    lines.push(`    cardFrame: ${art[m].cardFrame ? `"${art[m].cardFrame}"` : 'null'},`);
    lines.push(`    okBtn: "${art[m].okBtn}",`);
    lines.push(`    cancelBtn: "${art[m].cancelBtn}",`);
    lines.push(`    deckPowers: "${art[m].deckPowers}",`);
    lines.push(`  },`);
  }
  lines.push("};");

  fs.writeFileSync(OUT, lines.join("\n"), "utf8");
  const sizeMB = (fs.statSync(OUT).size / 1024 / 1024).toFixed(2);
  console.log(`\nWrote kq-joey-art.js (${sizeMB} MB)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
