"use strict";
const fs = require("fs");
const path = require("path");
const sharp = require("sharp");

const BASE = path.join(__dirname, "..", "Joey Assets", "LR");
const OUT = path.join(__dirname, "..", "kq-lr-ui-art.js");

async function webp(filename, w, h, quality = 88, fit = "inside") {
  const buf = await sharp(path.join(BASE, filename)).resize(w, h, { fit, withoutEnlargement: true, background: { r: 0, g: 0, b: 0, alpha: 0 } }).webp({ quality, effort: 4 }).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}
async function trim(filename, w, h, quality = 90) {
  const buf = await sharp(path.join(BASE, filename)).trim({ background: { r: 0, g: 0, b: 0, alpha: 0 } }).resize(w, h, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } }).webp({ quality, effort: 4 }).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

async function main() {
  const art = {};
  for (const [key, file] of Object.entries({ laneArith:"LR Arithmetic Marker.png", laneGeo:"LR Geometry Marker.png", laneLogic:"LR Logic Marker.png", laneSci:"LR Science Marker.png", laneSpeed:"LR Speed Marker.png" })) art[key] = await trim(file, 240, 100);
  art.dynamicLaneGlow = true;
  art.backBtn = await trim("LR Back.png", 300, 100);
  art.passBtn = await trim("LR Pass.png", 300, 100);
  art.okBtn = await trim("ok.png", 300, 100);
  art.cancelBtn = await trim("cancel.png", 300, 100);
  art.wonRound = await trim("LR Won Round.png", 100, 100);
  art.lostRound = await trim("LR Lost Round.png", 100, 100);
  art.round1 = await trim("LR Round 1.png", 600, 280);
  art.round2 = await trim("LR Round 2.png", 600, 280);
  art.round3 = await trim("LR Round 3.png", 600, 280);
  art.winBoard = await trim("LR You Win Round.png", 900, 620);
  art.loseBoard = await trim("LR You Lose Round.png", 900, 620);
  art.drawBoard = await trim("LR You Draw Round.png", 900, 620);
  art.mulligan = await trim("LR Mulligan.png", 720, 320);
  art.challenge = await trim("challenge.png", 520, 240);
  art.reveal = await trim("Reveal.png", 420, 220);
  art.friendly = await trim("Practice.png", 420, 220);
  art.winFinale = await webp("LR Won Finale.png", 1024, 576, 86, "cover");
  art.loseFinale = await webp("LR Lost Finale (1).png", 1024, 576, 86, "cover");
  art.drawFinale = await webp("LR Draw Finale.png", 1024, 576, 86, "cover");
  art.roundTracker = await trim("LR Round Score.png", 500, 320);
  art.scoreFrame = await trim("LR Scoreboard.png", 140, 100);
  art.battleLedger = await webp("LR Battle Ledger Complete.png", 724, 2172, 90, "fill");
  art.ingenuity = await trim("LR Ingenuity.png", 520, 200);
  art.powerUp = await trim("LR Power UP.png", 100, 100);
  art.powerDown = await trim("LR Power Down.png", 100, 100);
  art.nameFrame = await trim("LR Name Plate.png", 280, 80);
  art.playMat = await webp("LR Play Mat.png", 1672, 941, 84, "fill");
  art.frame3 = await webp("LR Frames 3 Identity Transparent.png", 1400, 1400, 90, "inside");
  art.laneBounds = [25.0, 41.7, 58.3, 75.0];
  art.laneTokenX = [33.35, 50.0, 66.65];
  art.ledgerLayout = { width:724, height:2172, powerXs:[408,492], upperPowerYs:[316,398,480,564,646], lowerPowerYs:[1258,1338,1420,1504,1586], setXs:[314,404,494], upperSetYs:[836,918,1000], lowerSetYs:[1840,1922,2004] };
  fs.writeFileSync(OUT, `// Generated by scripts/embed_lr_ui.cjs — do not edit by hand.\nexport const LR_UI_ART = ${JSON.stringify(art)};\n`);
}
main().catch(error => { console.error(error); process.exit(1); });
