"use strict";
const fs = require("fs");
const path = require("path");
const sharp = require("sharp");

const ROOT = path.join(__dirname, "..");
const ASSETS = path.join(ROOT, "assets", "card-lab");
const OUT = path.join(ROOT, "kq-card-lab-art.js");

async function data(file, width, height, quality, alpha) {
  const image = sharp(path.join(ASSETS, file)).resize(width, height, { fit: "cover" });
  const buffer = alpha
    ? await image.webp({ quality, effort: 4 }).toBuffer()
    : await image.jpeg({ quality }).toBuffer();
  return `data:image/${alpha ? "webp" : "jpeg"};base64,${buffer.toString("base64")}`;
}

async function transparentBinder() {
  const source = path.join(ASSETS, "9fo-binder-empty-v1.png");
  const { data: pixels, info } = await sharp(source).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const seen = new Uint8Array(info.width * info.height);
  const queue = [];
  const candidate = index => {
    const offset = index * 4;
    const red = pixels[offset], green = pixels[offset + 1], blue = pixels[offset + 2];
    return Math.max(red, green, blue) - Math.min(red, green, blue) < 14 && (red + green + blue) / 3 > 205;
  };
  const push = index => { if (!seen[index] && candidate(index)) { seen[index] = 1; queue.push(index); } };
  for (let x = 0; x < info.width; x++) { push(x); push((info.height - 1) * info.width + x); }
  for (let y = 0; y < info.height; y++) { push(y * info.width); push(y * info.width + info.width - 1); }
  for (let head = 0; head < queue.length; head++) {
    const index = queue[head], x = index % info.width, y = Math.floor(index / info.width);
    if (x) push(index - 1); if (x + 1 < info.width) push(index + 1);
    if (y) push(index - info.width); if (y + 1 < info.height) push(index + info.width);
  }
  for (let index = 0; index < seen.length; index++) if (seen[index]) pixels[index * 4 + 3] = 0;
  const buffer = await sharp(pixels, { raw: info }).resize(1536, 864, { fit: "fill" }).webp({ quality: 82, effort: 4 }).toBuffer();
  return `data:image/webp;base64,${buffer.toString("base64")}`;
}

async function main() {
  const background = await data("9fo-card-lab-orchard-background-v1.png", 1536, 864, 78, false);
  const binder = await transparentBinder();
  const pack = await data("9fo-pack-v1.png", 480, 640, 82, false);
  const rows = fs.readFileSync(path.join(ROOT, "card_data_export.tsv"), "utf8").trim().split(/\r?\n/);
  const headings = rows.shift().split("\t");
  const records = rows.map(line => Object.fromEntries(line.split("\t").map((value, index) => [headings[index], value])));
  const visibleName = name => name.replace(/\s*\(upgraded\)\s*$/i, "").trim();
  const filenameName = name => visibleName(name).replace(/[^A-Za-z0-9 ]/g, "").trim().replace(/\s+/g, "_");
  const fullCards = {};
  for (const module of ["Little Reckoning", "Gifford"]) {
    const moduleRows = records.filter(row => row.module === module && row.rarity !== "generic");
    const paired = new Set(moduleRows.filter(row => row.id.endsWith("_upgraded")).map(row => visibleName(row.name)));
    for (const row of moduleRows) {
      const prefix = module === "Little Reckoning" ? "LR" : "GF";
      const directory = module === "Little Reckoning" ? "little_reckoning_cards" : "gifford_cards";
      const name = visibleName(row.name);
      const suffix = row.id.endsWith("_upgraded") ? "_b" : paired.has(name) ? "_a" : "";
      const file = path.join(ROOT, "card_art", directory, `${prefix}_${filenameName(name)}${suffix}.png`);
      if (!fs.existsSync(file)) continue;
      const buffer = await sharp(file).resize(240, 360, { fit: "contain" }).webp({ quality: 78, effort: 4 }).toBuffer();
      fullCards[row.id] = `data:image/webp;base64,${buffer.toString("base64")}`;
    }
  }
  fs.writeFileSync(OUT, `// Generated by scripts/embed_card_lab_art.cjs — do not edit by hand.\nexport const CARD_LAB_ART = { background: ${JSON.stringify(background)}, binder: ${JSON.stringify(binder)}, pack: ${JSON.stringify(pack)}, fullCards: ${JSON.stringify(fullCards)} };\n`);
}

main().catch((error) => { console.error(error); process.exit(1); });
